<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWripvzi\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWripvzi/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerWripvzi.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerWripvzi\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerWripvzi\appProdProjectContainer([
    'container.build_hash' => 'Wripvzi',
    'container.build_id' => '6ed39b90',
    'container.build_time' => 1577962567,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWripvzi');
