<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerF9xlanj\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerF9xlanj/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerF9xlanj.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerF9xlanj\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerF9xlanj\appProdProjectContainer([
    'container.build_hash' => 'F9xlanj',
    'container.build_id' => '2801ea64',
    'container.build_time' => 1578049868,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerF9xlanj');
